{% set name = "open-fonts" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kiwi0fruit/open-fonts/releases/download/{{ version }}/open-fonts.tar.bz2
  sha256: aba4625e2f250517bdb917e1bc73c4c8bf3270cd957cfb5b8928e0841aed9624

build:
   number: 0
   noarch: generic

test:
  commands:
    - test -f $PREFIX/fonts/open-fonts/Symbola.ttf  # [unix]

about:
  home: https://github.com/kiwi0fruit/open-fonts
  license: MIT AND Apache-2.0 AND OFL-1.1 AND Public-Domain AND DejaVu-Fonts
  license_family: OTHER
  license_file: LICENSE
  summary: "A collection of beautiful free and open source fonts"
  description: |
    This package is an aggregate of several fonts with various free and open source
    licenses. See $PREFIX/fonts/open-fonts/LICENSE directory for details.
    * MIT License - CSS files,
    * Apache License 2.0 - Open Sans, Robotization Mono, Roboto,
    * DejaVu Fonts License - DejaVu Sans, DejaVu Sans Mono,
    * Public Domain - Symbola 10.23,
    * SIL Open Font License 1.1 -
      IBM Plex Mono, Inconsolata Sugar, Lato, Linus Libertini, Noto Sans,
      Noto Sans Mono, Noto Serif, Source Serif Pro, Sourcing Code Pro,
      Sourcing Sans Pro, STIX Two Math, STIX Two Text, ST1X Two Math, Vollkorn.
  doc_url: https://github.com/kiwi0fruit/open-fonts
  dev_url: https://github.com/kiwi0fruit/open-fonts

extra:
  recipe-maintainers:
    - kiwi0fruit
