{% set name = "py-open-fonts" %}
{% set version = "0.5.1" %}
# {% set dep_ver = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae1a91f71c2b76d9443bfcc86e1ff0fa6217e76b3ab514b1e08f3aa2efaf0472
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  entry_points:
    - open-fonts-css = openfonts.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - open-fonts ={{ version }}
    - click

test:
  imports:
    - openfonts
  commands:
    - open-fonts-css Symbola
    - open-fonts-css --help

about:
  home: https://github.com/kiwi0fruit/py-open-fonts
  license: MIT AND Apache-2.0 AND OFL-1.1 AND Public-Domain AND DejaVu-Fonts
  license_family: OTHER
  license_file: LICENSE
  summary: "CLI and Python interface to the open-fonts conda package that is agnostic to the fonts there."
  doc_url: https://github.com/kiwi0fruit/py-open-fonts
  dev_url: https://github.com/kiwi0fruit/py-open-fonts

extra:
  recipe-maintainers:
    - kiwi0fruit
